# Generated by Django 5.1.4 on 2024-12-31 19:13

import django.core.validators
import django.db.models.deletion
import jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, null=True)),
                ('description', models.TextField(default='', max_length=1000, null=True)),
                ('email', models.EmailField(default=True, max_length=100, null=True)),
                ('address', models.CharField(default=True, max_length=200, null=True)),
                ('salary', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('experience', models.CharField(choices=[('No Experience', 'No Experience'), ('1 Year', 'One Year'), ('2 Years', 'Two Year'), ('3 Years above', 'Three Year Plus')], default='3 Years above', max_length=20)),
                ('industry', models.CharField(choices=[('Business', 'Business'), ('IT', 'It'), ('Banking', 'Banking'), ('Education', 'Education'), ('Others', 'Others')], default='IT', max_length=20)),
                ('job_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Intership', 'Intership')], default='Permanent', max_length=20)),
                ('education', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Phd', 'Phd')], default='Bachelor', max_length=20)),
                ('positions', models.IntegerField(default=1)),
                ('company', models.CharField(default='', max_length=100, null=True)),
                ('last_date', models.DateTimeField(default=jobs.models.return_date_time)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
